### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by MurasameCyan** [jaw3l/tdm-nonvc#4]
![QQ_1720589492288](https://github.com/jaw3l/tdm-nonvc/assets/50967145/22e42b10-7528-4921-ae2d-e1891b17cede)
 got error

**Comment by jaw3l** [comment]
You might be using an `arm` device to run `x86-64` architecture. The current container image does not support ARM architecture, but I can implement multi-architecture images in the future. For now, you can build the image yourself and then run the container.

**Comment by MurasameCyan** [comment]
> You might be using an `arm` device to run `x86-64` architecture. The current container image does not support ARM architecture, but I can implement multi-architecture images in the future. For now, you can build the image yourself and then run the container.

oh, thx for your reply, pls add arm support and can you add mulit-account ?

**Comment by jaw3l** [comment]
You should be able to run the image now. 

Regarding the multi-account support, thanks for letting me know. Unfortunately, I am not planning to implement multi account feature. If there's anything else you need help with or any other features you're considering, feel free to share!

**Comment by MurasameCyan** [comment]
> You should be able to run the image now.
> 
> Regarding the multi-account support, thanks for letting me know. Unfortunately, I am not planning to implement multi account feature. If there's anything else you need help with or any other features you're considering, feel free to share!
 
thx but got new error

`
ln: failed to create symbolic link '/usr/src/app/cookies.jar': File exists
ln: failed to create symbolic link '/usr/src/app/settings.json': File exists
Traceback (most recent call last):
  File "main.py", line 17, in 
    import tkinter as tk
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 36, in 
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
`
![QQ_1720825020793](https://github.com/user-attachments/assets/879ebfb2-fd71-4aed-aac7-3014643aa216)

**Comment by jaw3l** [comment]
Even if I fix the missing library error on TDM, noVNC container still requires `amd64` device. I have to find a solution for that, too. For now, you can mitigate those errors by building the container images yourself.

**Comment by jaw3l** [comment]
Hello @MurasameCyan, apologies for the delayed update. It should be resolved with the latest version. I tested on my `aarch64` system but I will still be looking forward to your reply.

**Comment by MurasameCyan** [comment]
> Hello @MurasameCyan, apologies for the delayed update. It should be resolved with the latest version. I tested on my `aarch64` system but I will still be looking forward to your reply.

oh, it's work,but get new error.

`
Navigate to this URL:

    http://xxx:8080/vnc.html?host=xxx&port=8080

Press Ctrl-C to exit


    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 112, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0": [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 104, in get_socket
    s = _get_unix_socket(address)
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 82, in _get_unix_socket
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 108, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 76, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 26, in 
    from twitch import Twitch
  File "/usr/src/app/twitch.py", line 19, in 
    from gui import GUIManager
  File "/usr/src/app/gui.py", line 21, in 
    import pystray
  File "/usr/local/lib/python3.8/site-packages/pystray/__init__.py", line 64, in 
    Icon = backend().Icon
  File "/usr/local/lib/python3.8/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/usr/local/lib/python3.8/site-packages/pystray/__init__.py", line 36, in xorg
    from . import _xorg as backend; return backend
  File "/usr/local/lib/python3.8/site-packages/pystray/_xorg.py", line 36, in 
    display = Xlib.display.Display()
  File "/usr/local/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/usr/local/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 112, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0": [Errno 111] Connection refused
`
